# SPDX-FileCopyrightText: Copyright (C) 2026 Mauker and the Bespok3d contributors
# SPDX-License-Identifier: Apache-2.0

"""The thermal streamer, as importable modules.

Split out of a single hyphenated script (F-47): the name `thermal-master-stream.py` is a legal
program and an illegal module, so nothing could import it and mypy could not derive a module name
for it. The entry script keeps that name and this holds the code.

Everything public is re-exported here, so a caller can take the package as one namespace without
knowing which module a name lives in. The test suite does exactly that, which is what let the split
happen without touching a single test.
"""

from __future__ import annotations

# Surfaced deliberately although it belongs to the vendored driver. It is part of the capture
# path's contract: a marker mismatch is a glitched frame rather than a dead camera, and anything
# driving or testing that path has to be able to name it.
from p3_camera import FrameMarkerMismatchError  # type: ignore[import-not-found]

from .camera import (
    DEFAULT_GAIN,
    FRAME_IDLE_SLEEP_SECONDS,
    GAIN_DESCRIPTIONS,
    GAIN_HIGH,
    GAIN_LOW,
    GAIN_MODES,
    INITIAL_RECONNECT_DELAY_SECONDS,
    MAX_CONSECUTIVE_FRAME_FAILURES,
    MAX_RECONNECT_DELAY_SECONDS,
    RECONNECT_BACKOFF_FACTOR,
    SHUTTER_ACTION,
    SHUTTER_DONE,
    SHUTTER_FAILED,
    SHUTTER_FIELD,
    SHUTTER_IDLE,
    SHUTTER_PENDING,
    SUPPORTED_MODELS,
    VALID_GAINS,
    CameraNotFoundError,
    CameraSettings,
    CameraStalledError,
    DeviceController,
    capture_loop,
    detect_camera_model,
    fire_shutter,
    next_reconnect_delay,
    next_thermal_frame,
    release_camera,
    run_capture_session,
    stream_frames,
)
from .cli import (
    SHUTDOWN_GRACE_SECONDS,
    install_shutdown_handlers,
    main,
    parse_args,
)
from .overlay import (
    COLORBAR_HEIGHT_FRACTION,
    COLORBAR_MIN_WIDTH_PIXELS,
    COLORBAR_WIDTH_FRACTION,
    HOTSPOT_ARM_FRACTION,
    HOTSPOT_RGB,
    OVERLAY_FONT_HEIGHT_FRACTION,
    OVERLAY_MARGIN_FRACTION,
    OVERLAY_MIN_ENCODE_EDGE,
    OVERLAY_MIN_FONT_PIXELS,
    OVERLAY_SHADOW_RGB,
    OVERLAY_TEXT_RGB,
    RETICLE_ARM_FRACTION,
    RETICLE_RGB,
    WIDEST_TEMPERATURE_LABEL,
    Overlay,
    OverlayStyle,
    bar_position,
    clamp_label,
    draw_colorbar,
    draw_hotspot,
    draw_label,
    draw_overlay,
    draw_reticle,
    encode_upscale,
    glyph_advance,
    glyph_tile,
    label_width,
    mark_bar,
    marker_label_position,
    overlay_font,
    overlay_style,
)
from .page import (
    CONTROL_PAGE_TEMPLATE,
    CONTROL_SCRIPT,
    describe_device,
    render_control_page,
)
from .palettes import (
    DEFAULT_PALETTE,
    PALETTE_RAMPS,
    PALETTE_STEPS,
    PALETTE_TINTS,
    build_palettes,
    build_ramp_palette,
    build_tint_palette,
)
from .pipeline import (
    BOUNDS_SMOOTHING,
    DEFAULT_JPEG_QUALITY,
    DEFAULT_UPSCALE,
    DETAIL_STRENGTH,
    MIN_SPAN_RAW_COUNTS,
    NOISE_REDUCTION_WEIGHT,
    NORMALIZE_HIGH_PERCENTILE,
    NORMALIZE_LOW_PERCENTILE,
    VALID_ROTATIONS,
    RenderedFrame,
    RenderSettings,
    ThermalRenderer,
    blur_3x3,
    encode_jpeg,
    enhance_detail,
    frame_bounds,
    normalize_to_bytes,
    orient,
    reduce_temporal_noise,
    smooth_bounds,
)
from .server import (
    DEFAULT_BIND,
    DEFAULT_PORT,
    MJPEG_BOUNDARY,
    POST_ROUTES,
    ROUTES,
    SETTINGS_REDIRECT,
    STREAM_WAIT_SECONDS,
    LatestFrame,
    ThermalRequestHandler,
    ThermalServer,
    resolve_route,
)
from .settings import (
    RendererSource,
    SettingsStore,
    camera_settings_from_form,
    posted_emissivity,
    restored,
    settings_from_form,
)
from .temperature import (
    CELSIUS,
    DEFAULT_EMISSIVITY,
    DEFAULT_UNITS,
    EMISSIVITY_MATCH,
    EMISSIVITY_PRESETS,
    FAHRENHEIT,
    MAX_EMISSIVITY,
    MIN_EMISSIVITY,
    VALID_UNITS,
    FrameStats,
    format_temperature,
    frame_statistics,
    orient_point,
    rotate_point_clockwise,
    to_display_temperature,
)

__all__ = [
    "FrameMarkerMismatchError",
    "bar_position",
    "blur_3x3",
    "BOUNDS_SMOOTHING",
    "build_palettes",
    "build_ramp_palette",
    "build_tint_palette",
    "camera_settings_from_form",
    "CameraNotFoundError",
    "CameraSettings",
    "CameraStalledError",
    "capture_loop",
    "CELSIUS",
    "clamp_label",
    "COLORBAR_HEIGHT_FRACTION",
    "COLORBAR_MIN_WIDTH_PIXELS",
    "COLORBAR_WIDTH_FRACTION",
    "CONTROL_PAGE_TEMPLATE",
    "CONTROL_SCRIPT",
    "DEFAULT_BIND",
    "DEFAULT_EMISSIVITY",
    "DEFAULT_GAIN",
    "DEFAULT_JPEG_QUALITY",
    "DEFAULT_PALETTE",
    "DEFAULT_PORT",
    "DEFAULT_UNITS",
    "DEFAULT_UPSCALE",
    "describe_device",
    "DETAIL_STRENGTH",
    "detect_camera_model",
    "DeviceController",
    "draw_colorbar",
    "draw_hotspot",
    "draw_label",
    "draw_overlay",
    "draw_reticle",
    "EMISSIVITY_MATCH",
    "EMISSIVITY_PRESETS",
    "encode_jpeg",
    "encode_upscale",
    "enhance_detail",
    "FAHRENHEIT",
    "fire_shutter",
    "format_temperature",
    "frame_bounds",
    "FRAME_IDLE_SLEEP_SECONDS",
    "frame_statistics",
    "FrameStats",
    "GAIN_DESCRIPTIONS",
    "GAIN_HIGH",
    "GAIN_LOW",
    "GAIN_MODES",
    "glyph_advance",
    "glyph_tile",
    "HOTSPOT_ARM_FRACTION",
    "HOTSPOT_RGB",
    "INITIAL_RECONNECT_DELAY_SECONDS",
    "install_shutdown_handlers",
    "label_width",
    "LatestFrame",
    "main",
    "mark_bar",
    "marker_label_position",
    "MAX_CONSECUTIVE_FRAME_FAILURES",
    "MAX_EMISSIVITY",
    "MAX_RECONNECT_DELAY_SECONDS",
    "MIN_EMISSIVITY",
    "MIN_SPAN_RAW_COUNTS",
    "MJPEG_BOUNDARY",
    "next_reconnect_delay",
    "next_thermal_frame",
    "NOISE_REDUCTION_WEIGHT",
    "NORMALIZE_HIGH_PERCENTILE",
    "NORMALIZE_LOW_PERCENTILE",
    "normalize_to_bytes",
    "orient",
    "orient_point",
    "Overlay",
    "overlay_font",
    "OVERLAY_FONT_HEIGHT_FRACTION",
    "OVERLAY_MARGIN_FRACTION",
    "OVERLAY_MIN_ENCODE_EDGE",
    "OVERLAY_MIN_FONT_PIXELS",
    "OVERLAY_SHADOW_RGB",
    "overlay_style",
    "OVERLAY_TEXT_RGB",
    "OverlayStyle",
    "PALETTE_RAMPS",
    "PALETTE_STEPS",
    "PALETTE_TINTS",
    "parse_args",
    "POST_ROUTES",
    "posted_emissivity",
    "RECONNECT_BACKOFF_FACTOR",
    "reduce_temporal_noise",
    "release_camera",
    "render_control_page",
    "RenderedFrame",
    "RendererSource",
    "RenderSettings",
    "resolve_route",
    "restored",
    "RETICLE_ARM_FRACTION",
    "RETICLE_RGB",
    "rotate_point_clockwise",
    "ROUTES",
    "run_capture_session",
    "settings_from_form",
    "SETTINGS_REDIRECT",
    "SettingsStore",
    "SHUTDOWN_GRACE_SECONDS",
    "SHUTTER_ACTION",
    "SHUTTER_DONE",
    "SHUTTER_FAILED",
    "SHUTTER_FIELD",
    "SHUTTER_IDLE",
    "SHUTTER_PENDING",
    "smooth_bounds",
    "stream_frames",
    "STREAM_WAIT_SECONDS",
    "SUPPORTED_MODELS",
    "ThermalRenderer",
    "ThermalRequestHandler",
    "ThermalServer",
    "to_display_temperature",
    "VALID_GAINS",
    "VALID_ROTATIONS",
    "VALID_UNITS",
    "WIDEST_TEMPERATURE_LABEL",
]
